[package]
name = "link_checker"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking", "rustls-tls"] }
scraper = "0.22.0"
color-eyre = "0.6.3"
tokio = { version = "1.43.0", features = ["full"] }
