[package]
name = "trunk_hello_world"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.97"
web-sys = { version = "0.3.74", features = ["Window", "Document", "HtmlElement", "Text"] }
